-- CreateTable
CREATE TABLE `BusinessBlockPlan` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `year` INTEGER NOT NULL,
    `month` INTEGER NOT NULL,
    `quarter` INTEGER NULL,
    `brandId` INTEGER NULL,
    `businessBlock` VARCHAR(191) NOT NULL,
    `salesAmountBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `adSpendBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `productCostBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `otherCostBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `grossProfitBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `grossMargin` DECIMAL(18, 6) NULL,
    `roi` DECIMAL(18, 6) NULL,
    `monthOverMonth` DECIMAL(18, 6) NULL,
    `manualRating` VARCHAR(191) NULL,
    `manualActionSuggestion` TEXT NULL,
    `decisionOwner` VARCHAR(191) NULL,
    `decisionDeadline` DATETIME(3) NULL,
    `remark` TEXT NULL,
    `aiRating` VARCHAR(191) NULL,
    `aiSummary` TEXT NULL,
    `aiActionSuggestion` TEXT NULL,
    `aiRiskNotes` JSON NULL,
    `aiAnalysisStatus` VARCHAR(191) NOT NULL DEFAULT 'pending',
    `aiAnalyzedAt` DATETIME(3) NULL,
    `nextBudgetBase` DECIMAL(18, 2) NULL,
    `budgetAdjustAmount` DECIMAL(18, 2) NULL,
    `budgetAdjustRatio` DECIMAL(18, 6) NULL,
    `budgetAdjustReason` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `bbp_month_brand_block_unique`(`year`, `month`, `brandId`, `businessBlock`),
    INDEX `BusinessBlockPlan_year_month_idx`(`year`, `month`),
    INDEX `BusinessBlockPlan_brandId_idx`(`brandId`),
    INDEX `BusinessBlockPlan_businessBlock_idx`(`businessBlock`),
    INDEX `BusinessBlockPlan_aiAnalysisStatus_idx`(`aiAnalysisStatus`),
    INDEX `BusinessBlockPlan_decisionDeadline_idx`(`decisionDeadline`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BusinessWarning` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `year` INTEGER NOT NULL,
    `month` INTEGER NOT NULL,
    `brandId` INTEGER NULL,
    `businessBlock` VARCHAR(191) NOT NULL,
    `channelId` INTEGER NULL,
    `warningType` VARCHAR(191) NOT NULL,
    `warningLevel` VARCHAR(191) NOT NULL,
    `currentValue` DECIMAL(18, 2) NOT NULL DEFAULT 0,
    `monthOverMonth` DECIMAL(18, 6) NULL,
    `manualActionSuggestion` TEXT NULL,
    `aiActionSuggestion` TEXT NULL,
    `aiSummary` TEXT NULL,
    `aiRiskNotes` JSON NULL,
    `aiAnalysisStatus` VARCHAR(191) NOT NULL DEFAULT 'pending',
    `decisionOwner` VARCHAR(191) NULL,
    `decisionDeadline` DATETIME(3) NULL,
    `remark` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `BusinessWarning_year_month_idx`(`year`, `month`),
    INDEX `BusinessWarning_brandId_idx`(`brandId`),
    INDEX `BusinessWarning_businessBlock_idx`(`businessBlock`),
    INDEX `BusinessWarning_channelId_idx`(`channelId`),
    INDEX `BusinessWarning_warningLevel_idx`(`warningLevel`),
    INDEX `BusinessWarning_decisionDeadline_idx`(`decisionDeadline`),
    INDEX `BusinessWarning_aiAnalysisStatus_idx`(`aiAnalysisStatus`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
