ALTER TABLE `OrderItem`
  ADD COLUMN `purchaseCurrency` VARCHAR(191) NOT NULL DEFAULT 'CNY',
  ADD COLUMN `purchaseExchangeRate` DECIMAL(18, 6) NOT NULL DEFAULT 1,
  ADD COLUMN `purchaseCostBase` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `packagingCurrency` VARCHAR(191) NOT NULL DEFAULT 'CNY',
  ADD COLUMN `packagingExchangeRate` DECIMAL(18, 6) NOT NULL DEFAULT 1,
  ADD COLUMN `packagingCostBase` DECIMAL(18, 2) NOT NULL DEFAULT 0;
